"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = [
    { id: 1, content: `Pillage, then burn.` },
    { id: 2, content: `A Sergeant in motion outranks a Lieutenant who doesn't know what's going on.` },
    { id: 3, content: `An ordnance technician at a dead run outranks everybody.` },
    { id: 4, content: `Close air support covereth a multitude of sins.` },
    { id: 5, content: `Close air support and friendly fire should be easier to tell apart.` },
    { id: 6, content: `If violence wasn’t your last resort, you failed to resort to enough of it.` },
    { id: 7, content: `If the food is good enough, the grunts will stop complaining about the incoming fire.` },
    { id: 8, content: `Mockery and derision have their place. Usually, it's on the far side of the airlock.` },
    { id: 9, content: `Never turn your back on an enemy.` },
    { id: 10, content: `Sometimes the only way out is through. . . through the hull.` },
    { id: 11, content: `Everything is air-droppable at least once.` },
    { id: 12, content: `A soft answer turneth away wrath. Once wrath is looking the other way, shoot it in the head.` },
    { id: 13, content: `Do unto others.` },
    { id: 14, content: `"Mad Science" means never stopping to ask "what's the worst thing that could happen?"` },
    { id: 15, content: `Only you can prevent friendly fire.` },
    { id: 16, content: `Your name is in the mouth of others: be sure it has teeth.` },
    { id: 17, content: `The longer everything goes according to plan, the bigger the impending disaster.` },
    { id: 18, content: `If the officers are leading from in front, watch out for an attack from the rear.` },
    { id: 19, content: `The world is richer when you turn enemies into friends, but that's not the same as you being richer.` },
    { id: 20, content: `If you're not willing to shell your own position, you're not willing to win.` },
    { id: 21, content: `Give a man a fish, feed him for a day. Take his fish away and tell him he's lucky just to be alive, and he'll figure out how to catch another one for you to take tomorrow.` },
    { id: 22, content: `If you can see the whites of their eyes, somebody's done something wrong.` },
    { id: 23, content: `The company mess and friendly fire should be easier to tell apart` },
    { id: 24, content: `Any sufficiently advanced technology is indistinguishable from a big gun.` },
    { id: 25, content: `If a manufacturer's warranty covers the damage you did, you didn't do enough damage.` },
    { id: 26, content: `"Fire and Forget" is fine, provided you never actually forget.` },
    { id: 27, content: `Don't be afraid to be the first to resort to violence.` },
    { id: 28, content: `If the price of collateral damage is high enough, you might be able to get paid for bringing ammunition home with you.` },
    { id: 29, content: `The enemy of my enemy is my enemy's enemy. No more. No less.` },
    { id: 30, content: `A little trust goes a long way. The less you use, the further you'll go.` },
    { id: 31, content: `Only cheaters prosper.` },
    { id: 32, content: `Anything is amphibious if you can get it back out of the water.` },
    { id: 33, content: `If you're leaving tracks, you're being followed.` },
    { id: 34, content: `If you’re leaving scorch-marks, you need a bigger gun.` },
    { id: 35, content: `That which does not kill me has made a tactical error.` },
    { id: 36, content: `When the going gets tough, the tough call for close air support.` },
    { id: 37, content: `There is no "overkill." There is only "open fire" and "reload."` },
    { id: 38, content: `What's easy for you can still be hard on your clients.` },
    { id: 39, content: `There is a difference between spare parts and extra parts.` },
    { id: 40, content: `Not all good news is enemy action.` },
    { id: 41, content: `“Do you have a backup?” means “I can’t fix this.”` },
    { id: 42, content: `"They'll never expect this" means "I want to try something stupid."` },
    { id: 43, content: `If it's stupid and it works, it's still stupid and you're lucky.` },
    { id: 44, content: `If it will blow a hole in the ground, it will double as an entrenching tool.` },
    { id: 45, content: `The size of the combat bonus is inversely proportional to the likelihood of surviving to collect it.` },
    { id: 46, content: `Don’t try to save money by conserving ammunition.` },
    { id: 47, content: `Don't expect the enemy to cooperate in the creation of your dream engagement.` },
    { id: 48, content: `If it ain't broke, it hasn't been issued to the infantry.` },
    { id: 49, content: `Every client is one missed payment away from becoming a target` },
    { id: 50, content: `If it only works in exactly the way the manufacturer intended, it is defective.` },
    { id: 51, content: `Let them see you sharpen the sword before you fall on it.` },
    { id: 52, content: `The army you've got is never the army you want.` },
    { id: 53, content: `The intel you've got is never the intel you want.` },
    { id: 54, content: `It's only too many troops if you can't pay them.` },
    { id: 55, content: `It's only too many weapons if they're pointing in the wrong direction.` },
    { id: 56, content: `Infantry exists to paint targets for people with real guns.` },
    { id: 57, content: `Artillery exists to launch large chunks of budget at an enemy it cannot actually see.` },
    { id: 58, content: `The pen is mightiest when it writes orders for more swords.` },
    { id: 59, content: `"Two wrongs is probably not going to be enough."` },
    { id: 60, content: `Any weapon's rate of fire is inversely proportional to the number of available targets.` },
    { id: 61, content: `Don't bring big grenades into small rooms.` },
    { id: 62, content: `Anything labeled "This end toward enemy" is dangerous at both ends.` },
    { id: 63, content: `The brass knows how to do it by knowing who can do it.` },
    { id: 64, content: `An ounce of sniper is worth a pound of suppressing fire.` },
    { id: 65, content: `After the toss, be the one with the pin, not the one with the grenade.` },
    { id: 66, content: `Necessity is the mother of deception.` },
    { id: 67, content: `If you can't carry cash, carry a weapon.` },
    { id: 68, content: `Negotiating from a position of strength does not mean you shouldn’t also negotiate from a position near the exits.` },
    { id: 69, content: `Sometimes rank is a function of firepower.` },
    { id: 70, content: `Failure is not an option - it is mandatory. The option is whether or not to let failure be the last thing you do.` }
];
//# sourceMappingURL=maxims.js.map